Name: Product
Host: 0.0.0.0
Port: 8001

Mysql:
  DataSource: root:200317@tcp(localhost:3306)/mall?charset=utf8mb4&parseTime=true&loc=Asia%2FShanghai

CacheRedis:
  - Host: localhost:6379
    Type: node
    Pass: "123456"

Auth:
  AccessSecret: uOvKLmVfztaXGpNYd4Z0I1SiT7MweJhl
  AccessExpire: 86400

AdminAuth:
  AccessSecret: uOvKLmVfztaXGpNYd4Z0I1SiT7MweJhl
  AccessExpire: 86400

ProductRpc:
  Etcd:
    Hosts:
      - localhost:2379
    Key: product.rpc

# 静态文件服务配置
FileUpload:
  UploadPath: D:/graduation/FilmMall/service/product/api/uploads
  UrlPrefix: http://localhost:8001/uploads/