// Code generated by goctl. DO NOT EDIT.
package types

type OrderItem struct {
	Id           int64  `json:"id"`            // 订单商品ID
	OrderId      int64  `json:"order_id"`      // 订单ID
	Pid          int64  `json:"pid"`           // 商品ID
	ProductName  string `json:"product_name"`  // 商品名称
	ProductImage string `json:"product_image"` // 商品图片
	Price        int64  `json:"price"`         // 商品单价(分)
	Quantity     int64  `json:"quantity"`      // 购买数量
	Amount       int64  `json:"amount"`        // 商品总价(分)
}

type CreateOrderItem struct {
	Pid          int64  `json:"pid"`           // 商品ID
	ProductName  string `json:"product_name"`  // 商品名称
	ProductImage string `json:"product_image"` // 商品图片
	Price        int64  `json:"price"`         // 商品单价(分)
	Quantity     int64  `json:"quantity"`      // 购买数量
	Amount       int64  `json:"amount"`        // 商品总价(分)
}

type Order struct {
	Id          int64       `json:"id"`           // 订单ID
	Oid         string      `json:"oid"`          // 订单号
	Uid         int64       `json:"uid"`          // 用户ID
	AddressId   int64       `json:"address_id"`   // 收货地址ID
	TotalPrice  int64       `json:"total_price"`  // 订单总价(分)
	ShippingFee int64       `json:"shipping_fee"` // 运费(分)
	Status      int64       `json:"status"`       // 订单状态:0待付款,1待发货,2待收货,3已完成
	StatusDesc  string      `json:"status_desc"`  // 状态描述
	Remark      string      `json:"remark"`       // 订单备注
	Items       []OrderItem `json:"items"`        // 订单商品列表
	CreateTime  string      `json:"create_time"`  // 创建时间
	UpdateTime  string      `json:"update_time"`  // 更新时间
}

type CreateOrderReq struct {
	Uid         int64             `json:"uid"`          // 用户ID
	AddressId   int64             `json:"address_id"`   // 收货地址ID
	TotalPrice  int64             `json:"total_price"`  // 订单总价(分)
	ShippingFee int64             `json:"shipping_fee"` // 运费(分)
	Remark      string            `json:"remark"`       // 订单备注
	Items       []CreateOrderItem `json:"items"`        // 订单商品列表
	Status      int64             `json:"status"`       // 订单状态
}

type CreateOrderData struct {
	Id  int64  `json:"id"`  // 订单ID
	Oid string `json:"oid"` // 订单号
}

type CreateOrderResp struct {
	Code int64           `json:"code"`
	Msg  string          `json:"msg"`
	Data CreateOrderData `json:"data"`
}

type UpdateOrderReq struct {
	Id     int64 `path:"id"`     // 订单ID
	Status int64 `json:"status"` // 订单状态
}

type UpdateOrderResp struct {
	Code int64  `json:"code"`
	Msg  string `json:"msg"`
}

type DeleteOrderReq struct {
	Id int64 `path:"id"` // 订单ID
}

type DeleteOrderResp struct {
	Code int64  `json:"code"`
	Msg  string `json:"msg"`
}

type GetOrderReq struct {
	Id int64 `path:"id"` // 订单ID
}

type GetOrderResp struct {
	Code int64  `json:"code"`
	Msg  string `json:"msg"`
	Data Order  `json:"data"` // 订单信息
}

type ListOrderReq struct {
	Uid      int64 `form:"uid"`       // 用户ID
	Status   int64 `form:"status"`    // 订单状态
	Page     int64 `form:"page"`      // 页码
	PageSize int64 `form:"page_size"` // 每页数量
}

type ListOrderData struct {
	Total int64   `json:"total"` // 总数
	List  []Order `json:"list"`  // 订单列表
}

type ListOrderResp struct {
	Code int64         `json:"code"`
	Msg  string        `json:"msg"`
	Data ListOrderData `json:"data"`
}
