// Code generated by goctl. DO NOT EDIT.
package handler

import (
	"net/http"

	address "mall/service/address/api/internal/handler/address"
	"mall/service/address/api/internal/svc"

	"github.com/zeromicro/go-zero/rest"
)

func RegisterHandlers(server *rest.Server, serverCtx *svc.ServiceContext) {
	server.AddRoutes(
		[]rest.Route{
			{
				Method:  http.MethodPost,
				Path:    "/api/address/add",
				Handler: address.AddAddressHandler(serverCtx),
			},
			{
				Method:  http.MethodPost,
				Path:    "/api/address/update",
				Handler: address.UpdateAddressHandler(serverCtx),
			},
			{
				Method:  http.MethodPost,
				Path:    "/api/address/delete",
				Handler: address.DeleteAddressHandler(serverCtx),
			},
			{
				Method:  http.MethodGet,
				Path:    "/api/address/list",
				Handler: address.GetAddressListHandler(serverCtx),
			},
			{
				Method:  http.MethodPost,
				Path:    "/api/address/setDefault",
				Handler: address.SetDefaultAddressHandler(serverCtx),
			},
		},
		rest.WithJwt(serverCtx.Config.Auth.AccessSecret),
	)
}
