// Code generated by goctl. DO NOT EDIT.
package types

type FilmOrderItem struct {
	Id          int64  `json:"id"`            // 冲洗订单项ID
	FilmOrderId int64  `json:"film_order_id"` // 冲洗订单ID
	FilmType    string `json:"film_type"`     // 胶片类型
	FilmBrand   string `json:"film_brand"`    // 胶片品牌
	Size        string `json:"size"`          // 尺寸规格
	Quantity    int64  `json:"quantity"`      // 数量
	Price       int64  `json:"price"`         // 单价(分)
	Amount      int64  `json:"amount"`        // 总价(分)
	Remark      string `json:"remark"`        // 备注
}

type CreateFilmOrderItem struct {
	FilmType  string `json:"film_type"`  // 胶片类型
	FilmBrand string `json:"film_brand"` // 胶片品牌
	Size      string `json:"size"`       // 尺寸规格
	Quantity  int64  `json:"quantity"`   // 数量
	Price     int64  `json:"price"`      // 单价(分)
	Amount    int64  `json:"amount"`     // 总价(分)
	Remark    string `json:"remark"`     // 备注
}

type FilmOrder struct {
	Id          int64           `json:"id"`           // 订单ID
	Foid        string          `json:"foid"`         // 订单号
	Uid         int64           `json:"uid"`          // 用户ID
	AddressId   int64           `json:"address_id"`   // 收货地址ID
	ReturnFilm  bool            `json:"return_film"`  // 是否回寄底片
	TotalPrice  int64           `json:"total_price"`  // 冲洗总价(分)
	ShippingFee int64           `json:"shipping_fee"` // 运费(分)
	Status      int64           `json:"status"`       // 订单状态:0待付款,1冲洗处理中,2待收货,3已完成
	StatusDesc  string          `json:"status_desc"`  // 状态描述
	Remark      string          `json:"remark"`       // 订单备注
	Items       []FilmOrderItem `json:"items"`        // 订单项列表
	CreateTime  string          `json:"create_time"`  // 创建时间
	UpdateTime  string          `json:"update_time"`  // 更新时间
}

type CreateFilmOrderReq struct {
	Uid         int64                 `json:"uid"`          // 用户ID
	AddressId   int64                 `json:"address_id"`   // 收货地址ID
	ReturnFilm  bool                  `json:"return_film"`  // 是否回寄底片
	TotalPrice  int64                 `json:"total_price"`  // 冲洗总价(分)
	ShippingFee int64                 `json:"shipping_fee"` // 运费(分)
	Remark      string                `json:"remark"`       // 订单备注
	Items       []CreateFilmOrderItem `json:"items"`        // 订单项列表
	Status      int64                 `json:"status"`       // 订单状态
}

type CreateFilmOrderData struct {
	Id   int64  `json:"id"`   // 订单ID
	Foid string `json:"foid"` // 订单号
}

type CreateFilmOrderResp struct {
	Code int64               `json:"code"`
	Msg  string              `json:"msg"`
	Data CreateFilmOrderData `json:"data"`
}

type UpdateFilmOrderReq struct {
	Id         int64  `path:"id"`                   // 订单ID
	Status     int64  `json:"status,optional"`      // 订单状态
	AddressId  int64  `json:"address_id,optional"`  // 收货地址ID
	ReturnFilm bool   `json:"return_film,optional"` // 是否回寄底片
	Remark     string `json:"remark,optional"`      // 备注
}

type UpdateFilmOrderResp struct {
	Code int64  `json:"code"`
	Msg  string `json:"msg"`
}

type GetFilmOrderReq struct {
	Id int64 `path:"id"` // 订单ID
}

type GetFilmOrderResp struct {
	Code int64     `json:"code"`
	Msg  string    `json:"msg"`
	Data FilmOrder `json:"data"` // 订单信息
}

type ListFilmOrderReq struct {
	Uid      int64 `form:"uid,optional"`         // 用户ID
	Status   int64 `form:"status,optional"`      // 订单状态
	Page     int64 `form:"page,default=1"`       // 页码
	PageSize int64 `form:"page_size,default=10"` // 每页数量
}

type ListFilmOrderData struct {
	Total int64       `json:"total"` // 总数
	List  []FilmOrder `json:"list"`  // 订单列表
}

type ListFilmOrderResp struct {
	Code int64             `json:"code"`
	Msg  string            `json:"msg"`
	Data ListFilmOrderData `json:"data"`
}

type DeleteFilmOrderReq struct {
	Id int64 `path:"id"` // 订单ID
}

type DeleteFilmOrderResp struct {
	Code int64  `json:"code"`
	Msg  string `json:"msg"`
}

type FilmPriceList struct {
	Types  []FilmType  `json:"types"`  // 胶片类型列表
	Brands []FilmBrand `json:"brands"` // 胶片品牌列表
	Sizes  []FilmSize  `json:"sizes"`  // 胶片尺寸列表
}

type FilmType struct {
	Id   int64  `json:"id"`   // 类型ID
	Name string `json:"name"` // 类型名称
}

type FilmBrand struct {
	Id   int64  `json:"id"`   // 品牌ID
	Name string `json:"name"` // 品牌名称
}

type FilmSize struct {
	Id   int64  `json:"id"`   // 尺寸ID
	Name string `json:"name"` // 尺寸名称
}

type FilmPriceListResp struct {
	Code int64         `json:"code"`
	Msg  string        `json:"msg"`
	Data FilmPriceList `json:"data"`
}
