// Code generated by goctl. DO NOT EDIT.
package types

type CartItem struct {
	Id           int64   `json:"id"`
	ProductId    int64   `json:"productId"`
	Quantity     int     `json:"quantity"`
	Selected     bool    `json:"selected"`
	ProductName  string  `json:"productName"`
	ProductImage string  `json:"productImage"`
	Price        float64 `json:"price"`
	Stock        int     `json:"stock"`
}

type AddCartReq struct {
	ProductId int64 `json:"productId"`
	Quantity  int   `json:"quantity,optional"`
}

type RemoveCartReq struct {
	Id int64 `path:"id"`
}

type UpdateQuantityReq struct {
	Id       int64 `json:"id"`
	Quantity int   `json:"quantity"`
}

type UpdateSelectedReq struct {
	Id       int64 `json:"id"`
	Selected bool  `json:"selected"`
}

type CartListResp struct {
	List []CartItem `json:"list"`
}

type BaseResp struct {
	Code    int    `json:"code"`
	Message string `json:"message"`
}
