// Code generated by goctl. DO NOT EDIT.
package handler

import (
	"net/http"

	"mall/service/statistics/api/internal/svc"

	"github.com/zeromicro/go-zero/rest"
)

func RegisterHandlers(server *rest.Server, serverCtx *svc.ServiceContext) {
	server.AddRoutes(
		[]rest.Route{
			{
				Method:  http.MethodPost,
				Path:    "/hot-products",
				Handler: getHotProductsHandler(serverCtx),
			},
			{
				Method:  http.MethodPost,
				Path:    "/category-stats",
				Handler: getCategoryStatsHandler(serverCtx),
			},
			{
				Method:  http.MethodPost,
				Path:    "/user-behavior",
				Handler: getUserBehaviorHandler(serverCtx),
			},
			{
				Method:  http.MethodPost,
				Path:    "/user-activity",
				Handler: getUserActivityHandler(serverCtx),
			},
			{
				Method:  http.MethodPost,
				Path:    "/export",
				Handler: exportStatisticsHandler(serverCtx),
			},
		},
		rest.WithPrefix("/api/statistics"),
	)
}
