// Code generated by goctl. DO NOT EDIT.
package types

type CreateRequest struct {
	Name      string   `json:"name"`
	Desc      string   `json:"desc"`
	Stock     int64    `json:"stock"`
	Amount    int64    `json:"amount"`
	Status    int64    `json:"status"`
	ImageUrls []string `json:"imageUrls"` // 商品图片URL列表
}

type CreateResponse struct {
	Id int64 `json:"id"`
}

type UpdateRequest struct {
	Id        int64    `json:"id"`
	Name      string   `json:"name,optional"`
	Desc      string   `json:"desc,optional"`
	Stock     int64    `json:"stock"`
	Amount    int64    `json:"amount,optional"`
	Status    int64    `json:"status,optional"`
	ImageUrls []string `json:"imageUrls,optional"` // 商品图片URL列表
	MainImage string   `json:"mainImage,optional"` // 商品主图
}

type UpdateResponse struct {
}

type RemoveRequest struct {
	Id int64 `json:"id"`
}

type RemoveResponse struct {
}

type DetailRequest struct {
	Id int64 `json:"id"`
}

type DetailResponse struct {
	Id        int64    `json:"id"`
	Name      string   `json:"name"`
	Desc      string   `json:"desc"`
	Stock     int64    `json:"stock"`
	Amount    int64    `json:"amount"`
	Status    int64    `json:"status"`
	ImageUrls []string `json:"imageUrls"` // 商品图片URL列表
	MainImage string   `json:"mainImage"` // 商品主图
}

type Product struct {
	Id        int64    `json:"id"`
	Name      string   `json:"name"`
	Desc      string   `json:"desc"`
	Stock     int64    `json:"stock"`
	Amount    int64    `json:"amount"`
	Status    int64    `json:"status"`
	Images    []string `json:"images"`    // 商品图片URL列表
	MainImage string   `json:"mainImage"` // 商品主图
}

type AdminProductListRequest struct {
	Page     int64 `json:"page,optional"`
	PageSize int64 `json:"pageSize,optional"`
}

type AdminProductListData struct {
	Total int64     `json:"total"`
	List  []Product `json:"list"`
}

type AdminProductListResponse struct {
	Code int64                 `json:"code"`
	Msg  string                `json:"msg"`
	Data *AdminProductListData `json:"data"`
}

type AddProductImagesRequest struct {
	ProductId int64    `json:"productId"`
	ImageUrls []string `json:"imageUrls"`
}

type AddProductImagesResponse struct {
}

type RemoveProductImagesRequest struct {
	ProductId int64    `json:"productId"`
	ImageUrls []string `json:"imageUrls"`
}

type RemoveProductImagesResponse struct {
}

type SetMainImageRequest struct {
	ProductId int64  `json:"productId" validate:"required"`
	ImageUrl  string `json:"imageUrl" validate:"required"`
}

type SetMainImageResponse struct {
}

type UploadResponse struct {
	Url string `json:"url"`
}
