// Code generated by goctl. DO NOT EDIT.
package types

type CreateRequest struct {
	Name      string   `json:"name"`
	Desc      string   `json:"desc"`
	Stock     int64    `json:"stock"`
	Amount    int64    `json:"amount"`
	Status    int64    `json:"status"`
	ImageUrls []string `json:"imageUrls"` // 商品图片URL列表
}

type CreateData struct {
	Id int64 `json:"id"`
}

type CreateResponse struct {
	Code int64      `json:"code"`
	Msg  string     `json:"msg"`
	Data CreateData `json:"data"`
}

type UpdateRequest struct {
	Id        int64    `json:"id"`
	Name      string   `json:"name,optional"`
	Desc      string   `json:"desc,optional"`
	Stock     int64    `json:"stock"`
	Amount    int64    `json:"amount,optional"`
	Status    int64    `json:"status,optional"`
	ImageUrls []string `json:"imageUrls,optional"` // 商品图片URL列表
	MainImage string   `json:"mainImage,optional"` // 商品主图
}

type UpdateResponse struct {
	Code int64  `json:"code"`
	Msg  string `json:"msg"`
}

type RemoveRequest struct {
	Id int64 `json:"id"`
}

type RemoveResponse struct {
}

type DetailRequest struct {
	Id int64 `json:"id"`
}

type DetailResponse struct {
	Id        int64    `json:"id"`
	Name      string   `json:"name"`
	Desc      string   `json:"desc"`
	Stock     int64    `json:"stock"`
	Amount    int64    `json:"amount"`
	Status    int64    `json:"status"`
	ImageUrls []string `json:"imageUrls"` // 商品图片URL列表
	MainImage string   `json:"mainImage"` // 商品主图
}

type Product struct {
	Id        int64    `json:"id"`
	Name      string   `json:"name"`
	Desc      string   `json:"desc"`
	Stock     int64    `json:"stock"`
	Amount    int64    `json:"amount"`
	Status    int64    `json:"status"`
	Images    []string `json:"images"`    // 商品图片URL列表
	MainImage string   `json:"mainImage"` // 商品主图
}

type AdminProductListRequest struct {
	Page     int64 `json:"page,optional"`
	PageSize int64 `json:"pageSize,optional"`
}

type AdminProductListData struct {
	Total int64     `json:"total"`
	List  []Product `json:"list"`
}

type AdminProductListResponse struct {
	Code int64                 `json:"code"`
	Msg  string                `json:"msg"`
	Data *AdminProductListData `json:"data"`
}

type AddProductImagesRequest struct {
	ProductId int64    `json:"productId"`
	ImageUrls []string `json:"imageUrls"`
}

type AddProductImagesResponse struct {
}

type RemoveProductImagesRequest struct {
	ProductId int64    `json:"productId"`
	ImageUrls []string `json:"imageUrls"`
}

type RemoveProductImagesResponse struct {
}

type SetMainImageRequest struct {
	ProductId int64  `json:"productId" validate:"required"`
	ImageUrl  string `json:"imageUrl" validate:"required"`
}

type SetMainImageResponse struct {
}

type UploadResponse struct {
	Url string `json:"url"`
}

type ProductListRequest struct {
	Page     int64 `form:"page,optional"`
	PageSize int64 `form:"pageSize,optional"`
}

type ProductListData struct {
	Total int64     `json:"total"`
	List  []Product `json:"list"`
}

type ProductListResponse struct {
	Code int64            `json:"code"`
	Msg  string           `json:"msg"`
	Data *ProductListData `json:"data"`
}

type StockRequest struct {
	Id int64 `json:"id"`
}

type StockData struct {
	Stock int64 `json:"stock"`
}

type StockResponse struct {
	Code int64     `json:"code"`
	Msg  string    `json:"msg"`
	Data StockData `json:"data"`
}

type Banner struct {
	Id       int64  `json:"id"`
	ImageUrl string `json:"imageUrl"`
	Link     string `json:"link"`
}

type BannerListResponse struct {
	Code int64    `json:"code"`
	Msg  string   `json:"msg"`
	Data []Banner `json:"data"`
}

type GetProductImagesRequest struct {
	ProductId int64 `json:"productId"`
}

type ProductImageInfo struct {
	Id        int64  `json:"id"`
	ProductId int64  `json:"productId"`
	ImageUrl  string `json:"imageUrl"`
	IsMain    bool   `json:"isMain"`
}

type GetProductImagesResponse struct {
	Code int64              `json:"code"`
	Msg  string             `json:"msg"`
	Data []ProductImageInfo `json:"data"`
}
