// Code generated by goctl. DO NOT EDIT.
package handler

import (
	"net/http"

	"mall/service/product/api/internal/svc"

	"github.com/zeromicro/go-zero/rest"
)

func RegisterHandlers(server *rest.Server, serverCtx *svc.ServiceContext) {
	server.AddRoutes(
		[]rest.Route{
			{
				Method:  http.MethodGet,
				Path:    "/api/product/list",
				Handler: ProductListHandler(serverCtx),
			},
			{
				Method:  http.MethodPost,
				Path:    "/api/product/images/list",
				Handler: GetProductImagesHandler(serverCtx),
			},
			{
				Method:  http.MethodPost,
				Path:    "/api/product/detail",
				Handler: DetailHandler(serverCtx),
			},
		},
	)

	server.AddRoutes(
		[]rest.Route{
			{
				Method:  http.MethodPost,
				Path:    "/api/product/create",
				Handler: CreateHandler(serverCtx),
			},
			{
				Method:  http.MethodPost,
				Path:    "/api/product/update",
				Handler: UpdateHandler(serverCtx),
			},
			{
				Method:  http.MethodPost,
				Path:    "/api/product/remove",
				Handler: RemoveHandler(serverCtx),
			},
			{
				Method:  http.MethodPost,
				Path:    "/api/product/images/add",
				Handler: AddProductImagesHandler(serverCtx),
			},
			{
				Method:  http.MethodPost,
				Path:    "/api/product/images/remove",
				Handler: RemoveProductImagesHandler(serverCtx),
			},
			{
				Method:  http.MethodPost,
				Path:    "/api/product/images/setMain",
				Handler: SetMainImageHandler(serverCtx),
			},
			{
				Method:  http.MethodPost,
				Path:    "/api/upload",
				Handler: UploadHandler(serverCtx),
			},
		},
		rest.WithJwt(serverCtx.Config.Auth.AccessSecret),
	)

	server.AddRoutes(
		[]rest.Route{
			{
				Method:  http.MethodPost,
				Path:    "/api/admin/product/list",
				Handler: AdminProductListHandler(serverCtx),
			},
		},
		rest.WithJwt(serverCtx.Config.AdminAuth.AccessSecret),
	)
}
