// Code generated by goctl. DO NOT EDIT.
package types

type Address struct {
	Id         int64  `json:"id"`
	UserId     int64  `json:"userId"`
	Name       string `json:"name"`       // 收货人姓名
	Phone      string `json:"phone"`      // 联系电话
	Province   string `json:"province"`   // 省份
	City       string `json:"city"`       // 城市
	District   string `json:"district"`   // 区/县
	DetailAddr string `json:"detailAddr"` // 详细地址
	IsDefault  bool   `json:"isDefault"`  // 是否为默认地址
	CreateTime int64  `json:"createTime"`
	UpdateTime int64  `json:"updateTime"`
}

type AddAddressReq struct {
	Name       string `json:"name"`
	Phone      string `json:"phone"`
	Province   string `json:"province"`
	City       string `json:"city"`
	District   string `json:"district"`
	DetailAddr string `json:"detailAddr"`
	IsDefault  bool   `json:"isDefault"`
}

type AddAddressResp struct {
	Id int64 `json:"id"`
}

type UpdateAddressReq struct {
	Id         int64  `json:"id"`
	Name       string `json:"name,optional"`
	Phone      string `json:"phone,optional"`
	Province   string `json:"province,optional"`
	City       string `json:"city,optional"`
	District   string `json:"district,optional"`
	DetailAddr string `json:"detailAddr,optional"`
	IsDefault  bool   `json:"isDefault,optional"`
}

type DeleteAddressReq struct {
	Id int64 `json:"id"`
}

type GetAddressListResp struct {
	List []Address `json:"list"`
}

type SetDefaultAddressReq struct {
	Id int64 `json:"id"`
}
