// Code generated by goctl. DO NOT EDIT.
package types

type Work struct {
	Id           int64  `json:"id"`            // 作品ID
	Uid          int64  `json:"uid"`           // 用户ID
	Title        string `json:"title"`         // 作品标题
	Description  string `json:"description"`   // 作品描述
	CoverUrl     string `json:"cover_url"`     // 封面图URL
	FilmType     string `json:"film_type"`     // 胶片类型
	FilmBrand    string `json:"film_brand"`    // 胶片品牌
	Camera       string `json:"camera"`        // 相机型号
	Lens         string `json:"lens"`          // 镜头型号
	ExifInfo     string `json:"exif_info"`     // EXIF信息(JSON格式)
	ViewCount    int64  `json:"view_count"`    // 浏览次数
	LikeCount    int64  `json:"like_count"`    // 点赞数
	CommentCount int64  `json:"comment_count"` // 评论数
	Status       int64  `json:"status"`        // 状态:0草稿,1已发布,2已删除
	CreateTime   string `json:"create_time"`   // 创建时间
	UpdateTime   string `json:"update_time"`   // 更新时间
}

type WorkImage struct {
	Id         int64  `json:"id"`          // 图片ID
	WorkId     int64  `json:"work_id"`     // 作品ID
	Url        string `json:"url"`         // 图片URL
	Sort       int64  `json:"sort"`        // 排序
	CreateTime string `json:"create_time"` // 创建时间
}

type Like struct {
	Id         int64  `json:"id"`          // 点赞ID
	Uid        int64  `json:"uid"`         // 用户ID
	WorkId     int64  `json:"work_id"`     // 作品ID
	CreateTime string `json:"create_time"` // 创建时间
}

type Comment struct {
	Id         int64  `json:"id"`          // 评论ID
	Uid        int64  `json:"uid"`         // 用户ID
	WorkId     int64  `json:"work_id"`     // 作品ID
	Content    string `json:"content"`     // 评论内容
	ReplyId    int64  `json:"reply_id"`    // 回复的评论ID(为0表示顶级评论)
	Status     int64  `json:"status"`      // 状态:0正常,1已删除
	CreateTime string `json:"create_time"` // 创建时间
}

type CreateWorkReq struct {
	Title       string `json:"title"`       // 作品标题
	Description string `json:"description"` // 作品描述
	CoverUrl    string `json:"cover_url"`   // 封面图URL
	FilmType    string `json:"film_type"`   // 胶片类型
	FilmBrand   string `json:"film_brand"`  // 胶片品牌
	Camera      string `json:"camera"`      // 相机型号
	Lens        string `json:"lens"`        // 镜头型号
	ExifInfo    string `json:"exif_info"`   // EXIF信息(JSON格式)
	Status      int64  `json:"status"`      // 状态:0草稿,1已发布
}

type CreateWorkData struct {
	Id int64 `json:"id"` // 作品ID
}

type CreateWorkResp struct {
	Code int64          `json:"code"`
	Msg  string         `json:"msg"`
	Data CreateWorkData `json:"data"`
}

type UpdateWorkReq struct {
	Id          int64  `path:"id"`                   // 作品ID
	Title       string `json:"title,optional"`       // 作品标题
	Description string `json:"description,optional"` // 作品描述
	CoverUrl    string `json:"cover_url,optional"`   // 封面图URL
	FilmType    string `json:"film_type,optional"`   // 胶片类型
	FilmBrand   string `json:"film_brand,optional"`  // 胶片品牌
	Camera      string `json:"camera,optional"`      // 相机型号
	Lens        string `json:"lens,optional"`        // 镜头型号
	ExifInfo    string `json:"exif_info,optional"`   // EXIF信息(JSON格式)
	Status      int64  `json:"status,optional"`      // 状态:0草稿,1已发布,2已删除
}

type UpdateWorkResp struct {
	Code int64  `json:"code"`
	Msg  string `json:"msg"`
}

type GetWorkReq struct {
	Id int64 `path:"id"` // 作品ID
}

type GetWorkData struct {
	Work       Work        `json:"work"`        // 作品信息
	Images     []WorkImage `json:"images"`      // 作品图片
	LikeStatus bool        `json:"like_status"` // 当前用户是否点赞
	Author     UserSimple  `json:"author"`      // 作者信息
}

type UserSimple struct {
	Uid      int64  `json:"uid"`      // 用户ID
	Nickname string `json:"nickname"` // 昵称
	Avatar   string `json:"avatar"`   // 头像
}

type GetWorkResp struct {
	Code int64       `json:"code"`
	Msg  string      `json:"msg"`
	Data GetWorkData `json:"data"`
}

type ListWorkReq struct {
	Uid       int64  `form:"uid,optional"`         // 用户ID(查询指定用户的作品)
	Keyword   string `form:"keyword,optional"`     // 关键词(标题或描述)
	FilmType  string `form:"film_type,optional"`   // 胶片类型
	FilmBrand string `form:"film_brand,optional"`  // 胶片品牌
	Status    int64  `form:"status,optional"`      // 状态
	Page      int64  `form:"page,default=1"`       // 页码
	PageSize  int64  `form:"page_size,default=10"` // 每页数量
}

type ListWorkData struct {
	Total int64        `json:"total"` // 总数
	List  []WorkDetail `json:"list"`  // 作品列表
}

type WorkDetail struct {
	Work   Work       `json:"work"`   // 作品信息
	Author UserSimple `json:"author"` // 作者信息
}

type ListWorkResp struct {
	Code int64        `json:"code"`
	Msg  string       `json:"msg"`
	Data ListWorkData `json:"data"`
}

type UploadWorkImageReq struct {
	WorkId int64 `form:"work_id"`       // 作品ID
	Sort   int64 `form:"sort,optional"` // 排序
}

type UploadWorkImageData struct {
	Id  int64  `json:"id"`  // 图片ID
	Url string `json:"url"` // 图片URL
}

type UploadWorkImageResp struct {
	Code int64               `json:"code"`
	Msg  string              `json:"msg"`
	Data UploadWorkImageData `json:"data"`
}

type DeleteWorkImageReq struct {
	Id int64 `path:"id"` // 图片ID
}

type DeleteWorkImageResp struct {
	Code int64  `json:"code"`
	Msg  string `json:"msg"`
}

type LikeWorkReq struct {
	WorkId int64 `json:"work_id"` // 作品ID
	Action int64 `json:"action"`  // 动作:1点赞,0取消点赞
}

type LikeWorkData struct {
	IsLiked bool  `json:"is_liked"` // 是否已点赞
	Count   int64 `json:"count"`    // 点赞数量
}

type LikeWorkResp struct {
	Code int64        `json:"code"`
	Msg  string       `json:"msg"`
	Data LikeWorkData `json:"data"`
}

type CreateCommentReq struct {
	WorkId  int64  `json:"work_id"`           // 作品ID
	Content string `json:"content"`           // 评论内容
	ReplyId int64  `json:"reply_id,optional"` // 回复的评论ID(为0表示顶级评论)
}

type CreateCommentData struct {
	Id int64 `json:"id"` // 评论ID
}

type CreateCommentResp struct {
	Code int64             `json:"code"`
	Msg  string            `json:"msg"`
	Data CreateCommentData `json:"data"`
}

type ListCommentReq struct {
	WorkId   int64 `form:"work_id"`              // 作品ID
	Page     int64 `form:"page,default=1"`       // 页码
	PageSize int64 `form:"page_size,default=20"` // 每页数量
}

type ListCommentData struct {
	Total int64           `json:"total"` // 总数
	List  []CommentDetail `json:"list"`  // 评论列表
}

type CommentDetail struct {
	Comment Comment         `json:"comment"`          // 评论信息
	User    UserSimple      `json:"user"`             // 评论者信息
	Replies []CommentDetail `json:"replies,optional"` // 回复列表(仅顶级评论有此字段)
}

type ListCommentResp struct {
	Code int64           `json:"code"`
	Msg  string          `json:"msg"`
	Data ListCommentData `json:"data"`
}

type DeleteCommentReq struct {
	Id int64 `path:"id"` // 评论ID
}

type DeleteCommentResp struct {
	Code int64  `json:"code"`
	Msg  string `json:"msg"`
}

type DeleteWorkReq struct {
	Id int64 `path:"id"` // 作品ID
}

type DeleteWorkResp struct {
	Code int64  `json:"code"`
	Msg  string `json:"msg"`
}
