// Code generated by goctl. DO NOT EDIT.
package handler

import (
	"net/http"

	"mall/service/cart/api/internal/svc"

	"github.com/zeromicro/go-zero/rest"
)

func RegisterHandlers(server *rest.Server, serverCtx *svc.ServiceContext) {
	server.AddRoutes(
		[]rest.Route{
			{
				Method:  http.MethodPost,
				Path:    "/api/cart/add",
				Handler: AddCartHandler(serverCtx),
			},
			{
				Method:  http.MethodDelete,
				Path:    "/api/cart/:id",
				Handler: RemoveCartHandler(serverCtx),
			},
			{
				Method:  http.MethodPut,
				Path:    "/api/cart/quantity",
				Handler: UpdateQuantityHandler(serverCtx),
			},
			{
				Method:  http.MethodPut,
				Path:    "/api/cart/selected",
				Handler: UpdateSelectedHandler(serverCtx),
			},
			{
				Method:  http.MethodGet,
				Path:    "/api/cart/list",
				Handler: GetCartHandler(serverCtx),
			},
			{
				Method:  http.MethodDelete,
				Path:    "/api/cart/clear",
				Handler: ClearCartHandler(serverCtx),
			},
		},
		rest.WithJwt(serverCtx.Config.Auth.AccessSecret),
	)
}
