// Code generated by goctl. DO NOT EDIT.
package handler

import (
	"net/http"

	"mall/service/user/api/internal/svc"

	"github.com/zeromicro/go-zero/rest"
)

func RegisterHandlers(server *rest.Server, serverCtx *svc.ServiceContext) {
	server.AddRoutes(
		[]rest.Route{
			{
				Method:  http.MethodPost,
				Path:    "/api/user/login",
				Handler: LoginHandler(serverCtx),
			},
			{
				Method:  http.MethodPost,
				Path:    "/api/user/register",
				Handler: RegisterHandler(serverCtx),
			},
			{
				Method:  http.MethodPost,
				Path:    "/api/admin/login",
				Handler: AdminLoginHandler(serverCtx),
			},
		},
	)

	server.AddRoutes(
		[]rest.Route{
			{
				Method:  http.MethodPost,
				Path:    "/api/user/userinfo",
				Handler: UserInfoHandler(serverCtx),
			},
			{
				Method:  http.MethodPost,
				Path:    "/api/user/service/submit",
				Handler: SubmitServiceRequestHandler(serverCtx),
			},
			{
				Method:  http.MethodPost,
				Path:    "/api/user/service/list",
				Handler: ServiceListHandler(serverCtx),
			},
			{
				Method:  http.MethodPost,
				Path:    "/api/user/service/detail",
				Handler: ServiceDetailHandler(serverCtx),
			},
			{
				Method:  http.MethodPost,
				Path:    "/api/user/service/faq/list",
				Handler: FaqListHandler(serverCtx),
			},
			{
				Method:  http.MethodPost,
				Path:    "/api/chat/send",
				Handler: SendChatMessageHandler(serverCtx),
			},
			{
				Method:  http.MethodGet,
				Path:    "/api/chat/history",
				Handler: GetChatHistoryHandler(serverCtx),
			},
			{
				Method:  http.MethodGet,
				Path:    "/api/chat/connect",
				Handler: ChatConnectHandler(serverCtx),
			},
		},
		rest.WithJwt(serverCtx.Config.Auth.AccessSecret),
	)

	server.AddRoutes(
		[]rest.Route{
			{
				Method:  http.MethodPost,
				Path:    "/api/admin/create",
				Handler: CreateAdminHandler(serverCtx),
			},
			{
				Method:  http.MethodPost,
				Path:    "/api/admin/update",
				Handler: UpdateAdminHandler(serverCtx),
			},
			{
				Method:  http.MethodPost,
				Path:    "/api/admin/delete",
				Handler: DeleteAdminHandler(serverCtx),
			},
			{
				Method:  http.MethodPost,
				Path:    "/api/admin/info",
				Handler: AdminInfoHandler(serverCtx),
			},
			{
				Method:  http.MethodPost,
				Path:    "/api/admin/list",
				Handler: AdminListHandler(serverCtx),
			},
			{
				Method:  http.MethodPost,
				Path:    "/api/admin/chat/send",
				Handler: AdminSendChatMessageHandler(serverCtx),
			},
			{
				Method:  http.MethodGet,
				Path:    "/api/admin/chat/history",
				Handler: AdminGetChatHistoryHandler(serverCtx),
			},
			{
				Method:  http.MethodGet,
				Path:    "/api/admin/chat/sessions",
				Handler: AdminGetChatSessionsHandler(serverCtx),
			},
			{
				Method:  http.MethodGet,
				Path:    "/api/admin/chat/connect",
				Handler: AdminChatConnectHandler(serverCtx),
			},
			{
				Method:  http.MethodPost,
				Path:    "/api/admin/service/list",
				Handler: AdminServiceListHandler(serverCtx),
			},
			{
				Method:  http.MethodPost,
				Path:    "/api/admin/service/detail",
				Handler: AdminServiceDetailHandler(serverCtx),
			},
			{
				Method:  http.MethodPost,
				Path:    "/api/admin/service/update",
				Handler: AdminServiceUpdateHandler(serverCtx),
			},
			{
				Method:  http.MethodPost,
				Path:    "/api/admin/service/faq/add",
				Handler: AdminFaqAddHandler(serverCtx),
			},
			{
				Method:  http.MethodPost,
				Path:    "/api/admin/service/faq/update",
				Handler: AdminFaqUpdateHandler(serverCtx),
			},
			{
				Method:  http.MethodPost,
				Path:    "/api/admin/service/faq/delete",
				Handler: AdminFaqDeleteHandler(serverCtx),
			},
		},
		rest.WithJwt(serverCtx.Config.AdminAuth.AccessSecret),
	)
}
