// Code generated by goctl. DO NOT EDIT.
package handler

import (
	"net/http"

	"mall/service/user/api/internal/svc"

	"github.com/zeromicro/go-zero/rest"
)

func RegisterHandlers(server *rest.Server, serverCtx *svc.ServiceContext) {
	server.AddRoutes(
		[]rest.Route{
			{
				Method:  http.MethodPost,
				Path:    "/api/user/login",
				Handler: LoginHandler(serverCtx),
			},
			{
				Method:  http.MethodPost,
				Path:    "/api/user/register",
				Handler: RegisterHandler(serverCtx),
			},
			{
				Method:  http.MethodPost,
				Path:    "/api/admin/login",
				Handler: AdminLoginHandler(serverCtx),
			},
		},
	)

	server.AddRoutes(
		[]rest.Route{
			{
				Method:  http.MethodPost,
				Path:    "/api/user/userinfo",
				Handler: UserInfoHandler(serverCtx),
			},
		},
		rest.WithJwt(serverCtx.Config.Auth.AccessSecret),
	)

	server.AddRoutes(
		[]rest.Route{
			{
				Method:  http.MethodPost,
				Path:    "/api/admin/create",
				Handler: CreateAdminHandler(serverCtx),
			},
			{
				Method:  http.MethodPost,
				Path:    "/api/admin/update",
				Handler: UpdateAdminHandler(serverCtx),
			},
			{
				Method:  http.MethodPost,
				Path:    "/api/admin/delete",
				Handler: DeleteAdminHandler(serverCtx),
			},
			{
				Method:  http.MethodPost,
				Path:    "/api/admin/info",
				Handler: AdminInfoHandler(serverCtx),
			},
			{
				Method:  http.MethodPost,
				Path:    "/api/admin/list",
				Handler: AdminListHandler(serverCtx),
			},
		},
		rest.WithJwt(serverCtx.Config.AdminAuth.AccessSecret),
	)
}
