// Code generated by goctl. DO NOT EDIT.
package handler

import (
	"net/http"

	"mall/service/community/api/internal/svc"

	"github.com/zeromicro/go-zero/rest"
)

func RegisterHandlers(server *rest.Server, serverCtx *svc.ServiceContext) {
	server.AddRoutes(
		[]rest.Route{
			{
				Method:  http.MethodGet,
				Path:    "/work/:id",
				Handler: getWorkHandler(serverCtx),
			},
			{
				Method:  http.MethodGet,
				Path:    "/work/list",
				Handler: listWorkHandler(serverCtx),
			},
			{
				Method:  http.MethodGet,
				Path:    "/comment/list",
				Handler: listCommentHandler(serverCtx),
			},
		},
		rest.WithPrefix("/api/community"),
	)

	server.AddRoutes(
		[]rest.Route{
			{
				Method:  http.MethodPost,
				Path:    "/user/work",
				Handler: createWorkHandler(serverCtx),
			},
			{
				Method:  http.MethodPut,
				Path:    "/user/work/:id",
				Handler: updateWorkHandler(serverCtx),
			},
			{
				Method:  http.MethodGet,
				Path:    "/user/work/list",
				Handler: getUserWorksHandler(serverCtx),
			},
			{
				Method:  http.MethodPost,
				Path:    "/user/work/image/upload",
				Handler: uploadWorkImageHandler(serverCtx),
			},
			{
				Method:  http.MethodDelete,
				Path:    "/user/work/image/:id",
				Handler: deleteWorkImageHandler(serverCtx),
			},
			{
				Method:  http.MethodPost,
				Path:    "/user/like",
				Handler: likeWorkHandler(serverCtx),
			},
			{
				Method:  http.MethodPost,
				Path:    "/user/comment",
				Handler: createCommentHandler(serverCtx),
			},
			{
				Method:  http.MethodDelete,
				Path:    "/user/comment/:id",
				Handler: deleteCommentHandler(serverCtx),
			},
		},
		rest.WithJwt(serverCtx.Config.Auth.AccessSecret),
		rest.WithPrefix("/api/community"),
	)

	server.AddRoutes(
		[]rest.Route{
			{
				Method:  http.MethodGet,
				Path:    "/admin/work/:id",
				Handler: adminGetWorkHandler(serverCtx),
			},
			{
				Method:  http.MethodGet,
				Path:    "/admin/work/list",
				Handler: adminListWorkHandler(serverCtx),
			},
			{
				Method:  http.MethodPut,
				Path:    "/admin/work/:id",
				Handler: adminUpdateWorkHandler(serverCtx),
			},
			{
				Method:  http.MethodDelete,
				Path:    "/admin/comment/:id",
				Handler: adminDeleteCommentHandler(serverCtx),
			},
		},
		rest.WithJwt(serverCtx.Config.AdminAuth.AccessSecret),
		rest.WithPrefix("/api/community"),
	)
}
