// Code generated by goctl. DO NOT EDIT.
package types

type LoginRequest struct {
	Mobile   string `json:"mobile"`
	Password string `json:"password"`
}

type LoginResponse struct {
	AccessToken  string `json:"accessToken"`
	AccessExpire int64  `json:"accessExpire"`
}

type RegisterRequest struct {
	Name     string `json:"name"`
	Gender   int64  `json:"gender"`
	Mobile   string `json:"mobile"`
	Password string `json:"password"`
}

type RegisterResponse struct {
	Id     int64  `json:"id"`
	Name   string `json:"name"`
	Gender int64  `json:"gender"`
	Mobile string `json:"mobile"`
}

type UserInfoResponse struct {
	Id     int64  `json:"id"`
	Name   string `json:"name"`
	Gender int64  `json:"gender"`
	Mobile string `json:"mobile"`
}

type AdminLoginRequest struct {
	Username string `json:"username"`
	Password string `json:"password"`
}

type AdminLoginResponse struct {
	AccessToken  string `json:"accessToken"`
	AccessExpire int64  `json:"accessExpire"`
}

type CreateAdminRequest struct {
	Username string `json:"username"`
	Password string `json:"password"`
	Level    int32  `json:"level,optional"`
}

type CreateAdminResponse struct {
	Id       int64  `json:"id"`
	Username string `json:"username"`
	Level    int32  `json:"level"`
}

type UpdateAdminRequest struct {
	Id       int64  `json:"id"`
	Password string `json:"password"`
	Level    int32  `json:"level"`
}

type UpdateAdminResponse struct {
	Id       int64  `json:"id"`
	Username string `json:"username"`
	Level    int32  `json:"level"`
}

type DeleteAdminRequest struct {
	Id int64 `json:"id"`
}

type DeleteAdminResponse struct {
	Id       int64  `json:"id"`
	Username string `json:"username"`
	Level    int32  `json:"level"`
}

type AdminInfoResponse struct {
	Id       int64  `json:"id"`
	Username string `json:"username"`
	Level    int32  `json:"level"`
}
